### PR TITLE
fix label checker

### PR DESCRIPTION
**Pull request by AyodeAwe**
PR updates the label checker plugin to correctly skip Forward Merger PRs.

### CODE REVIEW

**Comment by AyodeAwe** [comment]
@ajschmidt8, regarding the `branch_checker` and `recently_updated` plugins, it appears the goal is to exclude release PRs. 

Could we do this (in a separate PR) by omitting PRs whose titles begin with [RELEASE], rather than by the authorship of GPUTester, as is currently done?

**Review by ajschmidt8 — APPROVED** [review]
Does the `GPUtester` open up any other PRs? If not, this PR looks good to me.

If so, we'll probably want to amend the logic to exclude PRs from both `GPUtester` and `rapids-bot`.

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
After reading your comment, we should probably exclude both `GPUtester` and `rapids-bot` PRs

**Comment by ajschmidt8** [comment]
> @ajschmidt8, regarding the `branch_checker` and `recently_updated` plugins, it appears the goal is to [exclude release PRs](https://github.com/rapidsai/ops-bot/blob/main/test/fixtures/responses/list_pulls.json#L5).
> 
> Could we do this (in a separate PR) by omitting PRs whose titles begin with [RELEASE], rather than by the authorship of GPUTester, as is currently done?
> 
> The logic would also be updated to omit PRs authored by `rapids-bot` as well.

Looking at the author is safer than looking at the PR title. Otherwise anyone could skip the checks, which is not what we want.

**Comment by AyodeAwe** [comment]
@ajschmidt8 GPUTester does not open any PRs. It used to though (e.g [here](https://github.com/rapidsai/rmm/pull/1240), in 2023). These days, the release PRs that come out of code freeze come authored by Ray (e.g [here](https://github.com/rapidsai/rmm/pull/1440))

I guess my question would be, seeing that release PRs are no longer authored by GPUTester but Ray, even if we include an exclusion of PRs from GPUTester, release PRs ([which seems to be what we have intended to exclude in the past](https://github.com/rapidsai/ops-bot/blob/main/test/branch_checker.test.ts#L52-L62)) will NOT be excluded.

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
> @ajschmidt8 GPUTester does not open any PRs. It used to though (e.g [here](https://github.com/rapidsai/rmm/pull/1240), in 2023). These days, the release PRs that come out of code freeze come authored by Ray (e.g [here](https://github.com/rapidsai/rmm/pull/1440))
> 
> I guess my question would be, seeing that release PRs are no longer authored by GPUTester but Ray, even if we include an exclusion of PRs from GPUTester, release PRs ([which seems to be what we have intended to exclude in the past](https://github.com/rapidsai/ops-bot/blob/main/test/branch_checker.test.ts#L52-L62)) will NOT be excluded from checks.

In that case, these changes are probably fine. I wasn't aware that Ray started opening release PRs now.

I don't think there's any good way to exclude release PRs so we can just punt on that problem for now.

**Pull request merged**
